/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\devilish_sword.glb 
Author: emmyalshafeay (https://sketchfab.com/emanalshafeay)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/devilish-sword-980567d47a59405e9d56834c63598cd6
Title: Devilish sword
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/devilish_sword.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.flame__0.geometry} material={materials.flame__0} />
        <mesh geometry={nodes.Devilish_sword_Material_0.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/devilish_sword.glb')
